### ISSUE TITLE
OID Parsing invalid for values > 0x50

### ISSUE THREAD

**Issue by sjthomsen** [PKISolutions/Asn1DerParser.NET#6] opened 2024-07-10 17:15 UTC
OID with byte value 06 04 82 4B 09 79 being parsed as 3.10.75.9.121 while openssl asnparse and other places parse the bytes as 2.251.9.121.

After much digging including the ITU-T X.690 specification. I have determined that the values allowed for the first number are 0, 1, or 2 and the variable length that is utilized for all other bytes also can apply to byte 0 with some special rules.

Consider the following examples:  First line for each block is the OID bytes.  Second is the current output.  Third is the expected output.
```
82 4B 09 79
3.10.75.9.121
2.251.9.121

88 37 89 52
3.16.55.1234
2.999.1234

82 00 09 79
3.10.0.9.121
2.176.9.121

79 00 09 79
3.1.0.9.121
2.81.0.9.121

88 37 03
3.16.55.3
2.999.3
```

Consider using this alternate decode block or modify to fit your coding style/needs.

```
public static String decode(Asn1Reader asn)
{
    var SB = new StringBuilder();

    Int32 pi = asn.PayloadStartOffset;

    BigInteger value = 0;
    BigInteger additional = 0;

    // if first byte value < 80
    if (asn[pi] > 0x50)
    {
        SB.Append("2");

        // single byte
        if (asn[pi] < 0x80)
        {
            SB.Append(".");
            SB.Append(asn[pi] - 0x28);
        }
        // multibyte
        else if (asn[pi] > 0x80)
        {
            value = ((asn[pi] & 0x7F) - 1);

            additional = 0x30;
        }
        // error, invalid value
        else
        {
            return "**Error**";
        }
    }
    else
    {
        SB.Append(asn[pi] / 0x28);
        SB.Append("." + asn[pi] % 0x28);
    }

    for (Int32 i = 1; i < asn.PayloadLength; i++)
    {
        pi = asn.PayloadStartOffset + i;

        value <<= 7;
        value += asn[pi] & 0x7f;

        if ((asn[pi] & 0x80) == 0)
        {
            value += additional;

            SB.Append("." + value);

            value = 0;
            additional = 0;
        }
        else if (i == asn.PayloadLength - 1)
        {
            // error, ends with 0x8X
            return "**Error**";
        }
    }

    return SB.ToString();
}
```

**Comment by Crypt32** [comment] 2024-07-11 07:48
Thanks for report! I will investigate this issue.

**Comment by Crypt32** [comment] 2024-08-01 10:47
I found that both, OID encoder and decoder were buggy. In addition, I found another bug (#7) which was also fixed.

Thanks for provided workaround and spent efforts, however I found a better and more optimal fix for this issue which required less changes while retaining existing logic. The issue is fixed and I've added a number of unit tests (including all your examples) to ensure its correctness.

**Closed** 2024-08-01 10:48 UTC
Labels: bug
